### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by UncleWael** [djjd47130/JD-TMDB#1]
Hello , 
Thank you for your efforts. 
While I'm trying out your test demo , it keeps reporting HTTP error 401 Unauthorized when login, as shown in attached screenshot.
of course I've included the openssl library in the deployment folder of the test demo,
a little help here will be appreciated.

Greetings.

 
![Untitled-1 copy](https://github.com/djjd47130/JD-TMDB/assets/86499283/c4f1b77a-77c9-411c-aca9-5b5ddb02ee99)

**Comment by djjd47130** [comment]
Hi,

This project is still in very raw development, and login is not yet supported. Currently, all development is related to unauthenticated (anonymous) users - not even the "Guest" option is expected to work at this time. Most requests will work, just not anything which requires an account / session.

**Comment by djjd47130** [comment]
> Hello , Thank you for your efforts. While I'm trying out your test demo , it keeps reporting HTTP error 401 Unauthorized when login, as shown in attached screenshot. of course I've included the openssl library in the deployment folder of the test demo, a little help here will be appreciated.
> 
> Greetings.
> 
> ![Untitled-1 copy](https://private-user-images.githubusercontent.com/86499283/329183223-c4f1b77a-77c9-411c-aca9-5b5ddb02ee99.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NzQ5NjgsIm5iZiI6MTcxODU3NDY2OCwicGF0aCI6Ii84NjQ5OTI4My8zMjkxODMyMjMtYzRmMWI3N2EtNzdjOS00MTFjLWFjYTktNWI1ZGRiMDJlZTk5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDIxNTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNzRjNzI1ZGY0YmFhZmY2ZTU5NGMzMDhiMzdmNTAxNTliMzVjZWMxOWRjMGRiYzQyMmUzMThlZjgzNjU1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9COKEfOa5LlYhou0jL3hMgbkfxKmK2wtZH8yu_ER1rE)

# UPDATE

The API wrapper(s) and application now support user authentication via either "Guest" or "Credentials". The preferred browser-based login is not yet implemented, but will consist of an event that must be handled to open a web browser of choice and monitor for a result. This way the wrapper does not require any direct ties to any web browsers, but leave that responsibility to the developer. But the test app even caches session ID and restores your user session when you launch it.
